# Generated by Django 4.2.13 on 2026-04-18 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conocimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PQRSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('radicado', models.CharField(editable=False, max_length=25, unique=True)),
                ('tipo', models.CharField(choices=[('peticion', 'Petición'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia'), ('denuncia', 'Denuncia'), ('correspondencia', 'Correspondencia')], max_length=20)),
                ('estado', models.CharField(choices=[('radicada', 'Radicada'), ('en_clasificacion', 'En Clasificación'), ('clasificada', 'Clasificada'), ('en_tramite', 'En Trámite'), ('respondida', 'Respondida'), ('cerrada', 'Cerrada')], default='radicada', max_length=20)),
                ('canal_entrada', models.CharField(choices=[('web', 'Portal Web'), ('email', 'Correo Electrónico'), ('whatsapp', 'WhatsApp'), ('instagram', 'Instagram'), ('presencial', 'Presencial')], max_length=20)),
                ('anonimo', models.BooleanField(default=False)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('nombre_ciudadano', models.CharField(blank=True, max_length=200)),
                ('email_ciudadano', models.EmailField(blank=True, max_length=254)),
                ('telefono_ciudadano', models.CharField(blank=True, max_length=20)),
                ('documento_ciudadano', models.CharField(blank=True, max_length=20)),
                ('comuna', models.CharField(blank=True, max_length=100)),
                ('barrio', models.CharField(blank=True, max_length=100)),
                ('asunto', models.CharField(max_length=300)),
                ('descripcion', models.TextField()),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='adjuntos/')),
                ('confianza_clasificacion', models.FloatField(blank=True, null=True)),
                ('clasificacion_validada', models.BooleanField(default=False)),
                ('fecha_radicacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('fecha_respuesta', models.DateTimeField(blank=True, null=True)),
                ('observaciones_funcionario', models.TextField(blank=True)),
                ('dependencia_asignada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqrsds_asignadas', to='conocimiento.dependencia')),
                ('dependencia_sugerida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqrsds_sugeridas', to='conocimiento.dependencia')),
                ('funcionario_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pqrsds_asignadas', to=settings.AUTH_USER_MODEL)),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'PQRSD',
                'verbose_name_plural': 'PQRSDs',
                'ordering': ['-fecha_radicacion'],
            },
        ),
    ]
