# Generated by Django 4.2.13 on 2026-04-19 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrsd',
            name='omnicanal_meta',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
