# Generated by Django 4.2.13 on 2026-04-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pqrsd', '0002_omnicanal_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pqrsd',
            name='canal_entrega',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pqrsd',
            name='descripcion_anonimizada',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pqrsd',
            name='observaciones_internas',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pqrsd',
            name='respuesta_automatica',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='pqrsd',
            name='respuesta_entregada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pqrsd',
            name='estado',
            field=models.CharField(choices=[('radicada', 'Radicada'), ('en_clasificacion', 'En Clasificación'), ('clasificada', 'Clasificada'), ('en_tramite', 'En Trámite'), ('respondida', 'Respondida'), ('cerrada', 'Cerrada'), ('rechazada', 'Rechazada')], default='radicada', max_length=20),
        ),
        migrations.AlterField(
            model_name='pqrsd',
            name='tipo',
            field=models.CharField(choices=[('peticion', 'Petición'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia'), ('denuncia', 'Denuncia'), ('correspondencia', 'Correspondencia'), ('felicitacion', 'Felicitación')], max_length=20),
        ),
    ]
