# Generated by Django 4.2.13 on 2026-04-18 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dependencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=30)),
                ('descripcion', models.TextField()),
                ('competencias', models.TextField(help_text='Lista de competencias separadas por punto y coma')),
                ('keywords', models.TextField(help_text='Palabras clave para clasificación IA, separadas por coma')),
                ('email_contacto', models.EmailField(blank=True, max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Dependencia',
                'verbose_name_plural': 'Dependencias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='PrecedenteRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pqrsd', models.CharField(choices=[('peticion', 'Petición'), ('queja', 'Queja'), ('reclamo', 'Reclamo'), ('sugerencia', 'Sugerencia'), ('denuncia', 'Denuncia'), ('correspondencia', 'Correspondencia')], max_length=20)),
                ('pregunta_frecuente', models.TextField()),
                ('respuesta_base', models.TextField()),
                ('normativa_aplicable', models.TextField(blank=True)),
                ('usado_veces', models.PositiveIntegerField(default=0)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('dependencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precedentes', to='conocimiento.dependencia')),
            ],
            options={
                'verbose_name': 'Precedente de Respuesta',
                'verbose_name_plural': 'Precedentes de Respuesta',
                'ordering': ['-usado_veces'],
            },
        ),
    ]
