# Generated by Django 4.2.13 on 2026-04-19 01:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conocimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fuente', models.CharField(default='medata', max_length=100)),
                ('registros_importados', models.PositiveIntegerField(default=0)),
                ('ejecutado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('exitoso', models.BooleanField(default=True)),
                ('error_msg', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Log de Sincronización',
                'verbose_name_plural': 'Logs de Sincronización',
                'ordering': ['-ejecutado_en'],
            },
        ),
    ]
