# Generated by Django 4.2.13 on 2026-04-18 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pqrsd', '0001_initial'),
        ('conocimiento', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SintesisPQRSD',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resumen_ejecutivo', models.TextField()),
                ('problema_central', models.TextField()),
                ('accion_requerida', models.TextField()),
                ('datos_contextuales', models.JSONField(default=dict)),
                ('entidades_mencionadas', models.JSONField(default=list)),
                ('normativa_aplicable', models.TextField(blank=True)),
                ('recomendacion_respuesta', models.TextField(blank=True)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('generado_por_ia', models.BooleanField(default=True)),
                ('pqrsd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sintesis', to='pqrsd.pqrsd')),
                ('precedentes_similares', models.ManyToManyField(blank=True, to='conocimiento.precedenterespuesta')),
            ],
            options={
                'verbose_name': 'Síntesis PQRSD',
                'verbose_name_plural': 'Síntesis PQRSD',
            },
        ),
    ]
