# Generated by Django 4.2.13 on 2026-04-18 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('conocimiento', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilFuncionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('enlace', 'Enlace PQRSD'), ('asesor_juridico', 'Asesor Jurídico'), ('director', 'Director de Dependencia'), ('admin', 'Administrador')], default='enlace', max_length=20)),
                ('cargo', models.CharField(blank=True, max_length=200)),
                ('dependencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='conocimiento.dependencia')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_funcionario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
