# Generated by Django 4.2.13 on 2026-04-18 23:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pqrsd', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClasificacionIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_enviado', models.TextField()),
                ('respuesta_cruda', models.TextField()),
                ('dependencias_sugeridas', models.JSONField(default=list)),
                ('tipo_sugerido', models.CharField(blank=True, max_length=20)),
                ('prioridad_sugerida', models.CharField(blank=True, max_length=10)),
                ('razon_clasificacion', models.TextField(blank=True)),
                ('confianza', models.FloatField(blank=True, null=True)),
                ('modelo_usado', models.CharField(default='gemini-1.5-flash', max_length=100)),
                ('fecha_clasificacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_validacion', models.DateTimeField(blank=True, null=True)),
                ('aceptada', models.BooleanField(blank=True, null=True)),
                ('comentario_validacion', models.TextField(blank=True)),
                ('pqrsd', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clasificacion_ia', to='pqrsd.pqrsd')),
                ('validado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clasificación IA',
                'verbose_name_plural': 'Clasificaciones IA',
            },
        ),
    ]
